# This workflow will be triggered on tags pushes and it
# will generate release notes using gren.

name: Generate release notes
on:
  push:
    tags:
      - '*'

jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup node environment
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      # Install gren
      - name: Install gren
        run: npm install github-release-notes@0.17.3 -g

      # Generate release notes
      - name: Generate release notes
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gren release --override